theme: jekyll-theme-minimal
title: Alpana Chaphalkar - DevOps Engineer & AI Enthusiast
description: Alpana's Resume, projects, courses, and professional journey in DevOps, AI, and software engineering.
